# Site settings
title: GLG Women's Retreat 2025
email: rpcwomensretreat@gmail.com
url: https://glgwomen.com/
description: "Reformed Presbyterian Church GLG Women's Retreat"
keywords: "Christian, Woman, Conference, Presbyterian, Reformed, Retreat"
subtitle: "Who Am I? Getting to the Heart of our Identity"
meta_author: David Daniels 
speaker: Sharon Sampson
topic: "Who Am I? Getting to the Heart of our Identity"
location: '<a href="https://maps.app.goo.gl/okUC3vVoZ8yzvjX46" target="_blank">Sycamore RPC</a>'
dates: October 10th and 11th 2025
opening_registration:  TBD

welcome_text: ""

bio: "Sharon Sampson is a member of the Grace RP Church in Gibsonia, PA, where her husband Mark serves as a ruling elder. She enjoys teaching the 1st-3rd grade church school class and helping to lead the Titus 2 women’s group. Sharon earned a Master of Theological Studies degree (biblical counseling concentration) from RPTS where she also worked for ten years." 

bio_link: '<a href="#portfolioModal-1" clasks="portfolio-link" data-toggle="modal">Read more</a>' 

schedule_soon: '
    <div class="col-lg-8 col-lg-offset-2 text-center">
        <h3>Coming Soon!</h3>
    </div>
'

schedule: "
    <div class='col-lg-4 col-lg-offset-2'>
        <h3 class='text-center'>Friday, October 11th</h3>
        <p>2:30-Early Arrival Fellowship</p>
        <p>5:00-Registration Opens</p>
        <p>6:00-Dinner</p>
        <p>7:00-<b>Session 1 </b></p>
        <p>8:15-Organized Activity</p>
        <p>8:45-Games, Fellowship, &amp; Snacks</p>
    </div>
    <div class='col-lg-4'>
        <h3 class='text-center'>Saturday, October 12th</h3>
        <p>8:00-Light Breakfast</p>
        <p>9:00-<b>Session 2</b></p>
        <p>10:00-Individual Reflection Time</p>
        <p>11:00-Brunch (Provided)</p>
        <p>12:00-<b>Session 3</b></p>
        <p>1:00-Fellowship Time</p>
        <p>1:45-Testimony</p>
        <p>2:45-Closing Remarks and Goodbyes</p>
    </div>
"

menu_soon: '
    <div class="col-lg-8 col-lg-offset-2 text-center">
        <h3>Coming Soon!</h3>
    </div>
'

menu: '
    <div class="col-lg-8 col-lg-offset-2 text-center">
        <h3>Friday Dinner</h3>
            <p>Chicken</p>
            <p>Mashed Potatoes with Gravy</p>
            <p>Green Beans</p>
            <p>Dinner Rolls</p>
            <p>Salad Bar</p>
            <p>Dessert</p>
            <p>Water/Iced Tea</p>
        <h3>Light Breakfast</h3>
            <p>Fresh Fruit</p>
            <p>Granola Bars</p>
            <p>Yogurt Cups</p>
            <p>Boiled Eggs</p>
            <p>Coffee/Water</p>
        <h3>Brunch</h3>
            <p>Scrambled Eggs</p>
            <p>Sausage Links</p>
            <p>Ham</p>
            <p>French Toast Sticks</p>
            <p>Quiche</p>
            <p>Fruit</p>
            <p>Yogurt Bar</p>
            <p>Coffee/Milk/Juice</p>
    </div>
'

info_soon: '
    <div class="row">
    </div>
'

info: '
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2>Information</h2>
            <hr class="star-light">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-lg-offset-2">
            <div class="padding"></div>

            <p>
            <b>What to Bring: </b>
            1. Your own bedding (air mattresses will be provided) <br>
            2. Bible and Psalter <br>
            3. Notebook and Pen <br>
            4. Personal Items <br>
            5. Flashlight <br>
            </p>

            <p><b>Arrival: </b>
            For early fellowship time come down to the basement and enjoy games and fellowship. Registration will open at 5:00 and is located at the main floor entrance to the sanctuary.
            </p>

            <p><b>Accommodations:</b> 
            The retreat is being held at Sycamore RP Church (300 E Mulberry Street, Kokomo, IN 46901). Classrooms will be available for sleeping space (with air mattresses). There is limited availability for staying at the church. First come, first serve. If you plan on staying at a hotel you must schedule that on your own. We recommend the Hampton Inn & Suites in Kokomo. 
            </p>
        </div>
        <div class="col-lg-4 text-center">
            <h3>Questions?</h3>
            <p>Please email all questions to:</p>
            <p><a href="mailto:rpcwomensretreat@gmail.com">RPCWomensRetreat@gmail.com</a></p>
            <p><b>Finances an issue?</b> Please talk to your local church about financial assistance.</p>
        </div>
        <div class="col-lg-4 text-center">
            <h3>More Info:</h3>
            Follow us on our Facebook page for more up to date info @rpcwomensretreat
        </div>
        <div class="col-lg-4 text-center">
            <h3>Location:</h3>
            Sycamore RPC
            300 E Mulberry St
            Kokomo, IN 46901
        </div>
    </div>
'


registration_soon: '
        <span class="registration_link">
        Coming Soon!
        </span>
'

registration: '
        <span class="registration_link">
        <a target="_blank" href="https://2rp.church/rpcwomensretreat/">Click here to register!</a>
        </span>
        <br /><br />
        <p>
        $55 by September 20th ($40 for Saturday only)
        $65 after September 20th ($50 for Saturday Only)
        </p>
        <p>
        Mail Check to:
        135 N Seminary St, Bloomfield, IN 47424<br/>
        or pay upon arrival (cash or check.)
        Make Check Payable to Second Reformed Presbyterian Church<br />
        </p>
'
recommendation_soon: '
        <span class="registration_link">
        Coming Soon!
        </span>
'

recommendation: '
        <span class="registration_link">
        <a target="_blank" href="https://2rp.church/2024-glg-womens-retreat-book-recommendations/">Book Recommendations from our Speakers</a>
        </span>
'

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: GLG Women's Retreat

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/rpcwomensretreat


# Postal address (add as many lines as necessary)
address:
  - line: 4800 N. Michigan Road
  - line: Indianapolis, Indiana 46228
  
# Credits content
credits: "GLG Women's Retreat is a ministry of 
<a href='https://www.sycamorerpc.org/' target='_blank'>Sycamore RPC</a> and <a href='https://www.2rp.church/' target='_blank'>2RP</a>"

# Build settings
markdown: kramdown
permalink: pretty
