# Site settings
title: RPC Women's Retreat 2024
email: rpcwomensretreat@gmail.com
url: https://glgwomen.com/
description: "Reformed Presbyterian Church GLG Women's Retreat"
keywords: "Christian, Woman, Conference, Presbyterian, Reformed, Retreat"
subtitle: "Mental Health and Community"
meta_author: David Daniels 
speaker: Creation Desautels
topic: "Mental Health and Community"
location: '<a href="https://maps.app.goo.gl/okUC3vVoZ8yzvjX46" target="_blank">Sycamore RPC</a>'
dates: November 1st and 2nd 2024
opening_registration: Nov 1st 6:00pm
closing_remarks: Nov 2nd 2:45pm

welcome_text: "We are really looking forward to this year's retreat, in growing in our love for the Lord, and deepening in our knowledge of His Word. We hope to see you there!"

bio: "Creation Desautels is a Licensed Marriage and Family Therapist in the state of Indiana.  She has a MA from Liberty university.  Her clinical background includes community mental health, family preservation services as well as private practice.  Post-degree Creation has pursued extensive specialized training and mentoring in the areas of faith integration, sex-therapy, and a variety of modalities including..." 

bio_link: '<a href="#portfolioModal-1" clasks="portfolio-link" data-toggle="modal">Read more</a>' 

schedule_coming_soon: '
    <div class="col-lg-8 col-lg-offset-2 text-center">
        <h3>Coming Soon!</h3>
    </div>
'

schedule: "
    <div class='col-lg-4 col-lg-offset-2'>
        <h3 class='text-center'>Friday</h3>
        <p>2:30-Registration</p>
        <p>6:00-Dinner (Provided)</p>
        <p>7:00-<b>Session 1 </b></p>
        <p>8:15-Organized Activity</p>
        <p>8:45-Games, Fellowship, &amp; Snacks</p>
    </div>
    <div class='col-lg-4'>
        <h3 class='text-center'>Saturday</h3>
        <p>8:00-Light Breakfast (Provided)</p>
        <p>9:00-<b>Session 2</b></p>
        <p>10:00-Individual Reflection Time</p>
        <p>11:00-Brunch (Food Provided)</p>
        <p>12:00-<b>Session 3</b></p>
        <p>1:00-Fellowship Time</p>
        <p>Q & A With Creation</p>
        <p>2:45-Closing Remarks and Goodbyes</p>
    </div>
"

menu_coming_soon: '
    <div class="col-lg-8 col-lg-offset-2 text-center">
        <h3>Coming Soon!</h3>
    </div>
'

menu: '
    <div class="col-lg-8 col-lg-offset-2 text-center">
        <h3>Friday Dinner</h3>
            <p>Chicken</p>
            <p>Mashed Potatoes with Gravy</p>
            <p>Green Beans</p>
            <p>Dinner Rolls</p>
            <p>Salad Bar</p>
            <p>Dessert</p>
            <p>Water/Iced Tea</p>
        <h3>Light Breakfast</h3>
            <p>Fresh Fruit</p>
            <p>Granola Bars</p>
            <p>Yogurt Cups</p>
            <p>Boiled Eggs</p>
            <p>Coffee/Water</p>
        <h3>Brunch</h3>
            <p>Scrambled Eggs</p>
            <p>Sausage Links</p>
            <p>Ham</p>
            <p>French Toast Sticks</p>
            <p>Quiche</p>
            <p>Fruit</p>
            <p>Yogurt Bar</p>
            <p>Coffee/Milk/Juice</p>
    </div>
'

info: '
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2>Information</h2>
            <hr class="star-light">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-lg-offset-2">
            <div class="padding"></div>
            <p><b>What to Bring</b>: Your own bedding: twin sheets, blankets, pillows (A twin air mattress will be available for those staying at the church.) Note: no showers available at church. You will need bible, pen, notebook, personal items, and favorite game.</p>
            <p><b>Arrival:</b> Check in at the registration table at the back entrance and settle in.</p>
            <p><b>Meals:</b> Dinner on Friday and a light breakfast and brunch on Saturday will be provided. </p>
            <p><b>Accommodations:</b> 
                To keep costs down, Sycamore Reformed Presbyeterian Church is hosting the Women's retreat again. There is limited availability to sleep at the building at no cost on a first-come, first-serve basis.
            </p>
        </div>
        <div class="col-lg-4 text-center">
            <h3>Questions?</h3>
            <p>Please direct questions to:</p>
            <p><a href="mailto:rpcwomensretreat@gmail.com">RPCWomensRetreat@gmail.com</a></p>
            <p>or</p>
            <p>
            Addie Bell (765) 438-6198
            </p>
            <p>
            Michele Daniels (765) 441-2503
            </p>
            <p>
            Ruth Rowe (812) 241-2468
            </p>
            <p>
            Tricia Watkins (765) 667-9981
            </p>
            <p><b>Finances an issue?</b> Please talk to your local church about financial assistance.</p>
        </div>
    
    </div>
'

registration: '
        <span class="registration_link">
            <a target="_blank" href="">Click here to register!</a>
        </span>
        <br /><br />
        <span>
        <p>
        Early Bird Registration (By October 14th): $55  ($40 Saturday Only)
        Registration (After October 14th): $65 ($50 Saturday Only)
        <p>
            Mail Check to:
            Second Reformed Presbyterian Church
        </p>
        <span class="skills">Or bring cash or check (payable to Immanuel Reformed Presybterian Church) with you to the retreat.</span>
'

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: GLG Women's Retreat

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/rpcwomensretreat

# Postal address (add as many lines as necessary)
address:
  - line: 300 E Mulberry St
  - line: Elkhart, Indiana 46901

# Credits content
credits: "GLG Women's Retreat is a ministry of <a href='http://www.sycamorerpc.org/' target='_blank'>Sycamore RPC</a>"

# Build settings
markdown: kramdown
permalink: pretty
