# Site settings
title: GLG Women's Retreat 2024
email: rpcwomensretreat@gmail.com
url: https://glgwomen.com/
description: "Reformed Presbyterian Church GLG Women's Retreat"
keywords: "Christian, Woman, Conference, Presbyterian, Reformed, Retreat"
subtitle: "Mental Health and Community"
meta_author: David Daniels 
speaker: Creation Desautels
topic: "Mental Health and Community"
location: '<a href="https://maps.app.goo.gl/okUC3vVoZ8yzvjX46" target="_blank">Sycamore RPC</a>'
dates: November 1st and 2nd 2024
opening_registration:  August 1st

welcome_text: "We are looking forward to this year's retreat. Our prayer is that it will be a chance to slow down, laying aside your daily duties for a couple of days. We hope to provide moments to connect with one another and reflect as individuals and as women within the body of Christ. During this pause, we will offer speakers and workshops designed to help you become more equipped, educated, and encouraged as women of faith. We hope to see you there!"

bio: "Creation Desautels is a Licensed Marriage and Family Therapist in the state of Indiana.  She has a MA from Liberty university.  Her clinical background includes community mental health, family preservation services as well as private practice.  Post-degree Creation has pursued extensive specialized training and mentoring in the areas of faith integration, sex-therapy, and a variety of modalities including..." 

bio_link: '<a href="#portfolioModal-1" clasks="portfolio-link" data-toggle="modal">Read more</a>' 

schedule_coming_soon: '
    <div class="col-lg-8 col-lg-offset-2 text-center">
        <h3>Coming Soon!</h3>
    </div>
'

schedule: "
    <div class='col-lg-4 col-lg-offset-2'>
        <h3 class='text-center'>Friday</h3>
        <p>2:30-Early Arrival Fellowship and Game Time</p>
        <p>5:00-Registration Opens</p>
        <p>6:00-Dinner (Provided)</p>
        <p>7:00-<b>Session 1 </b></p>
        <p>8:15-Organized Activity</p>
        <p>8:45-Games, Fellowship, &amp; Snacks</p>
    </div>
    <div class='col-lg-4'>
        <h3 class='text-center'>Saturday</h3>
        <p>8:00-Light Breakfast (Provided)</p>
        <p>9:00-<b>Session 2</b></p>
        <p>10:00-Individual Reflection Time</p>
        <p>11:00-Brunch (Food Provided)</p>
        <p>12:00-<b>Session 3</b></p>
        <p>1:00-Fellowship Time</p>
        <p>Q & A With Creation</p>
        <p>2:45-Closing Remarks and Goodbyes</p>
    </div>
"

menu_coming_soon: '
    <div class="col-lg-8 col-lg-offset-2 text-center">
        <h3>Coming Soon!</h3>
    </div>
'

menu: '
    <div class="col-lg-8 col-lg-offset-2 text-center">
        <h3>Friday Dinner</h3>
            <p>Chicken</p>
            <p>Mashed Potatoes with Gravy</p>
            <p>Green Beans</p>
            <p>Dinner Rolls</p>
            <p>Salad Bar</p>
            <p>Dessert</p>
            <p>Water/Iced Tea</p>
        <h3>Light Breakfast</h3>
            <p>Fresh Fruit</p>
            <p>Granola Bars</p>
            <p>Yogurt Cups</p>
            <p>Boiled Eggs</p>
            <p>Coffee/Water</p>
        <h3>Brunch</h3>
            <p>Scrambled Eggs</p>
            <p>Sausage Links</p>
            <p>Ham</p>
            <p>French Toast Sticks</p>
            <p>Quiche</p>
            <p>Fruit</p>
            <p>Yogurt Bar</p>
            <p>Coffee/Milk/Juice</p>
    </div>
'

info: '
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2>Information</h2>
            <hr class="star-light">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-lg-offset-2">
            <div class="padding"></div>

            <p>
            <b>What to Bring: </b>
            Bible, pen, notebook, personal items, and a favorite game. If you are staying at the church bring your own bedding: twin sheets, blankets, pillows (A twin air mattress will be available for those staying at the church.) Note: no showers available at church.
            </p>

            <p><b>Arrival: </b>
            For early fellowships time come down to the basement and enjoy games and fellowship. Registration will open at 5:00 and is located on the main floor entrance to the sanctuary.
            </p>

            <p>
            <b>Meals: </b>
            Dinner on Friday and a light breakfast and brunch on Saturday will be provided.
            </p>

            <p><b>Accommodations:</b> 
                To keep costs down, Sycamore Reformed Presbyeterian Church is hosting the Womens retreat again. There is limited availability to sleep at the building at no cost on a first-come, first-serve basis.
            </p>
        </div>
        <div class="col-lg-4 text-center">
            <h3>Questions?</h3>
            <p>Please direct questions to:</p>
            <p><a href="mailto:rpcwomensretreat@gmail.com">RPCWomensRetreat@gmail.com</a></p>
            <p>or</p>
            <p>
            Addie Bell (765) 438-6198
            </p>
            <p>
            Michele Daniels (765) 441-2503
            </p>
            <p>
            Ruth Rowe (812) 241-2468
            </p>
            <p>
            Tricia Watkins (765) 667-9981
            </p>
            <p><b>Finances an issue?</b> Please talk to your local church about financial assistance.</p>
        </div>
    </div>
'


registration: '
        <span class="registration_link">
        <a target="_blank" href="">Click here to register!</a>
        </span>
        <br /><br />
        <p>
        Early Bird Registration (By October 14th): $55  ($40 Saturday Only)
        </p>
        <p>
        Registration (After October 14th): $65 ($50 Saturday Only)
        </p>
        <p>
        Mail Check to:
        Ruth Rowe<br />
        135 N Seminary St, Bloomfield, IN 47424<br />
        Make Check Payable to Second Reformed Presbyterian Church<br />
        </p>
        <span class="skills">Or bring cash or check (payable to Second Reformed Presybterian Church) with you to the retreat.</span>
'

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: GLG Women's Retreat

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
url: https://www.facebook.com/rpcwomensretreat

# Postal address (add as many lines as necessary)
address:
  - line: 4800 N. Michigan Road
  - line: Indianapolis, Indiana 46228
  
# Credits content
credits: "GLG Women's Retreat is a ministry of 
<a href='https://www.sycamorerpc.org/' target='_blank'>Sycamore RPC</a> and <a href='https://www.2rp.church/' target='_blank'>2RP</a>"

# Build settings
markdown: kramdown
permalink: pretty
